export const endpoints = {
    me: '/api/v1/me',
    dashboard: '/api/v1/dashboard/summary',
    productMeta: '/api/v1/inventory/products/meta',
    products: '/api/v1/inventory/products',
    quickCompany: '/api/v1/inventory/companies/quick',
    quickUnit: '/api/v1/inventory/units/quick',
    quickCategory: '/api/v1/inventory/categories/quick',
    salesProductLookup: '/api/v1/sales/product-lookup',
    mrPerformance: '/api/v1/mr/performance',
    importTargets: '/api/v1/imports/targets',
    importPreview: '/api/v1/imports/preview',
    importConfirm: '/api/v1/imports/confirm',
    featureCatalog: '/api/v1/setup/features',
    setupInvites: '/api/v1/setup/invites',
    setupStatus: '/setup/status',
    setupComplete: '/setup/complete',
    updateCheck: '/api/v1/system/update-check',
};
