import { appUrl } from '../utils/url';

export const endpoints = {
    me: appUrl('/api/v1/me'),
    dashboard: appUrl('/api/v1/dashboard/summary'),
    profile: appUrl('/api/v1/profile'),
    productMeta: appUrl('/api/v1/inventory/products/meta'),
    products: appUrl('/api/v1/inventory/products'),
    quickCompany: appUrl('/api/v1/inventory/companies/quick'),
    quickUnit: appUrl('/api/v1/inventory/units/quick'),
    quickCategory: appUrl('/api/v1/inventory/categories/quick'),
    inventoryMaster: (master) => appUrl(`/api/v1/inventory/masters/${master}`),
    inventoryMasterRestore: (master, id) => appUrl(`/api/v1/inventory/masters/${master}/${id}/restore`),
    inventoryMasterExport: (master) => appUrl(`/api/v1/exports/inventory/masters/${master}`),
    inventoryProductsExport: appUrl('/api/v1/exports/inventory/products'),
    inventoryBatchesExport: appUrl('/api/v1/exports/inventory/batches'),
    inventoryBatches: appUrl('/api/v1/inventory/batches'),
    inventoryBatchOptions: appUrl('/api/v1/inventory/batches/options'),
    stockAdjustments: appUrl('/api/v1/inventory/stock-adjustments'),
    stockMovements: appUrl('/api/v1/inventory/stock-movements'),
    suppliers: appUrl('/api/v1/suppliers'),
    supplierOptions: appUrl('/api/v1/suppliers/options'),
    customers: appUrl('/api/v1/customers'),
    customerOptions: appUrl('/api/v1/customers/options'),
    purchaseOrders: appUrl('/api/v1/purchase/orders'),
    purchases: appUrl('/api/v1/purchases'),
    purchaseReturns: appUrl('/api/v1/purchase/returns'),
    purchaseReturnPurchases: appUrl('/api/v1/purchase/returns/purchases'),
    purchaseReturnItems: (purchaseId) => appUrl(`/api/v1/purchase/returns/purchases/${purchaseId}/items`),
    purchaseReturnBatches: appUrl('/api/v1/purchase/returns/batches'),
    salesProductLookup: appUrl('/api/v1/sales/product-lookup'),
    salesInvoices: appUrl('/api/v1/sales/invoices'),
    mrOptions: appUrl('/api/v1/mr/options'),
    mrRepresentatives: appUrl('/api/v1/mr/representatives'),
    mrVisits: appUrl('/api/v1/mr/visits'),
    mrPerformance: appUrl('/api/v1/mr/performance'),
    vouchers: appUrl('/api/v1/accounting/vouchers'),
    reports: appUrl('/api/v1/reports'),
    importTargets: appUrl('/api/v1/imports/targets'),
    importPreview: appUrl('/api/v1/imports/preview'),
    importConfirm: appUrl('/api/v1/imports/confirm'),
    featureCatalog: appUrl('/api/v1/setup/features'),
    branding: appUrl('/api/v1/setup/branding'),
    roles: appUrl('/api/v1/setup/roles'),
    users: appUrl('/api/v1/setup/users'),
    setupStatus: appUrl('/setup/status'),
    setupComplete: appUrl('/setup/complete'),
    updateCheck: appUrl('/api/v1/system/update-check'),
};
