export const countries = [
    { code: 'NP', name: 'Nepal', currency: 'NPR', symbol: 'Rs.' },
    { code: 'IN', name: 'India', currency: 'INR', symbol: '₹' },
    { code: 'US', name: 'United States', currency: 'USD', symbol: '$' },
    { code: 'GB', name: 'United Kingdom', currency: 'GBP', symbol: '£' },
    { code: 'AU', name: 'Australia', currency: 'AUD', symbol: 'A$' },
    { code: 'CA', name: 'Canada', currency: 'CAD', symbol: 'C$' },
    { code: 'EU', name: 'Eurozone', currency: 'EUR', symbol: '€' },
    { code: 'JP', name: 'Japan', currency: 'JPY', symbol: '¥' },
    { code: 'CN', name: 'China', currency: 'CNY', symbol: '¥' },
    { code: 'AE', name: 'United Arab Emirates', currency: 'AED', symbol: 'د.إ' },
    { code: 'AF', name: 'Afghanistan', currency: 'AFN', symbol: '؋' },
    { code: 'AL', name: 'Albania', currency: 'ALL', symbol: 'L' },
    { code: 'AM', name: 'Armenia', currency: 'AMD', symbol: '֏' },
    { code: 'AO', name: 'Angola', currency: 'AOA', symbol: 'Kz' },
    { code: 'AR', name: 'Argentina', currency: 'ARS', symbol: '$' },
    { code: 'AT', name: 'Austria', currency: 'EUR', symbol: '€' },
    { code: 'AZ', name: 'Azerbaijan', currency: 'AZN', symbol: '₼' },
    { code: 'BD', name: 'Bangladesh', currency: 'BDT', symbol: '৳' },
    { code: 'BE', name: 'Belgium', currency: 'EUR', symbol: '€' },
    { code: 'BR', name: 'Brazil', currency: 'BRL', symbol: 'R$' },
    { code: 'CH', name: 'Switzerland', currency: 'CHF', symbol: 'CHF' },
    { code: 'ID', name: 'Indonesia', currency: 'IDR', symbol: 'Rp' },
    { code: 'IL', name: 'Israel', currency: 'ILS', symbol: '₪' },
    { code: 'KR', name: 'South Korea', currency: 'KRW', symbol: '₩' },
    { code: 'LK', name: 'Sri Lanka', currency: 'LKR', symbol: 'Rs' },
    { code: 'MY', name: 'Malaysia', currency: 'MYR', symbol: 'RM' },
    { code: 'NG', name: 'Nigeria', currency: 'NGN', symbol: '₦' },
    { code: 'PK', name: 'Pakistan', currency: 'PKR', symbol: 'Rs' },
    { code: 'PH', name: 'Philippines', currency: 'PHP', symbol: '₱' },
    { code: 'RU', name: 'Russia', currency: 'RUB', symbol: '₽' },
    { code: 'SA', name: 'Saudi Arabia', currency: 'SAR', symbol: 'SR' },
    { code: 'SG', name: 'Singapore', currency: 'SGD', symbol: 'S$' },
    { code: 'TH', name: 'Thailand', currency: 'THB', symbol: '฿' },
    { code: 'TR', name: 'Turkey', currency: 'TRY', symbol: '₺' },
    { code: 'VN', name: 'Vietnam', currency: 'VND', symbol: '₫' },
    { code: 'ZA', name: 'South Africa', currency: 'ZAR', symbol: 'R' },
    // Add more countries as needed...
].sort((a, b) => a.name.localeCompare(b.name));

export const countryOptions = countries.map(c => ({
    value: c.code,
    label: `${c.name} (${c.symbol})`,
    symbol: c.symbol,
    currency: c.currency
}));
